logging:
  level: DEBUG
  loggers:
    "io.dropwizard": INFO
    "org.hibernate.type": TRACE
    "org.hibernate.SQL": TRACE
  appenders:
    - type: file
      # The file to which current statements will be logged.
      currentLogFilename: ./logs/example.log

      # When the log file rotates, the archived log will be renamed to this and gzipped. The
      # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
      # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
      archivedLogFilenamePattern: ./logs/example-%d.log.gz

      # The number of archived files to keep.
      archivedFileCount: 5

      # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
      timeZone: UTC
      
server:
  rootPath: /api/
  adminMinThreads: 1
  adminMaxThreads: 64
  applicationContextPath: /messenger
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 8080
   # - type: https
   #   port: 8443
   #   keyStorePath: example.keystore
   #   keyStorePassword: example
   #   validateCerts: false
  adminConnectors:
    - type: http
      port: 8081
    # - type: https
    #  port: 8444
    #  keyStorePath: example.keystore
    #  keyStorePassword: example
    #  validateCerts: false

# views:
  # .ftl:
    # strict_syntax: yes
    
database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: root

  # the password
  password: mysql

  # the JDBC URL
  url: jdbc:mysql://127.0.0.1:3306/jaxrs

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate.show_sql: true
    hibernate.format_sql: true
    hibernate.use_sql_comments: true
    hibernate.hbm2ddl.auto: update
    
  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

# user defined conifg
template: Hello, %s!
defaultName: Messenger

serviceConfig:
  paytm:
    host: paytm.in
    port: 80
  mobikwik:
    host: mobiwik.in
    port: 80